apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lmixpyfu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/go-lmixpyfu:f04bb06a71e3e02985f8de994c0a744eaa2ad61a@sha256:c1e0ada260afbd3cd97e5ea5324b28ee6b4088904e9ecd218d867d046d21694e
          name: container-image
